[package]
name = "oled_display"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dora-node-api = "0.3.11"
linux-embedded-hal = "0.4.0"
oled = {path="../../oled"} 
